# Generated by Django 3.2.8 on 2021-11-02 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CV_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_w', models.CharField(max_length=1024)),
                ('skill_t', models.CharField(max_length=1024)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SKILL_cv', to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_o', models.CharField(max_length=50)),
                ('job_l', models.CharField(max_length=50)),
                ('job_sd', models.CharField(max_length=20)),
                ('job_ed', models.CharField(max_length=20)),
                ('job_r', models.CharField(max_length=50)),
                ('job_d', models.CharField(max_length=1024)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='JOB_cv', to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_s', models.CharField(max_length=100)),
                ('edu_d', models.CharField(max_length=100)),
                ('edu_sd', models.CharField(max_length=20)),
                ('edu_ed', models.CharField(max_length=20)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='EDU_cv', to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('lang', models.CharField(blank=True, max_length=1024, null=True)),
                ('intro_text', models.CharField(max_length=1024)),
                ('outro_text', models.CharField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='BIO_cv', to='app.cv')),
            ],
        ),
    ]
