# Generated by Django 3.2.8 on 2022-01-28 05:02

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CV_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='J_Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_r', models.CharField(max_length=50)),
                ('role_l', models.CharField(blank=True, max_length=50, null=True)),
                ('role_d', models.CharField(blank=True, max_length=1024, null=True)),
                ('role_sdm', models.CharField(blank=True, choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('March', 'March'), ('Apr', 'Apr'), ('June', 'June'), ('July', 'July'), ('Aug', 'Aug'), ('Sept', 'Sept'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec'), ('Present', 'Present')], default='Jan', max_length=9, null=True)),
                ('role_sdy', models.CharField(blank=True, choices=[('1950', '1950'), ('1951', '1951'), ('1952', '1952'), ('1953', '1953'), ('1954', '1954'), ('1955', '1955'), ('1956', '1956'), ('1957', '1957'), ('1958', '1958'), ('1959', '1959'), ('1960', '1960'), ('1961', '1961'), ('1962', '1962'), ('1963', '1963'), ('1964', '1964'), ('1965', '1965'), ('1966', '1966'), ('1967', '1967'), ('1968', '1968'), ('1969', '1969'), ('1970', '1970'), ('1971', '1971'), ('1972', '1972'), ('1973', '1973'), ('1974', '1974'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('Present', 'Present')], default='2022', max_length=9, null=True)),
                ('role_edm', models.CharField(blank=True, choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('March', 'March'), ('Apr', 'Apr'), ('June', 'June'), ('July', 'July'), ('Aug', 'Aug'), ('Sept', 'Sept'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec'), ('Present', 'Present')], default='Jan', max_length=9, null=True)),
                ('role_edy', models.CharField(blank=True, choices=[('1950', '1950'), ('1951', '1951'), ('1952', '1952'), ('1953', '1953'), ('1954', '1954'), ('1955', '1955'), ('1956', '1956'), ('1957', '1957'), ('1958', '1958'), ('1959', '1959'), ('1960', '1960'), ('1961', '1961'), ('1962', '1962'), ('1963', '1963'), ('1964', '1964'), ('1965', '1965'), ('1966', '1966'), ('1967', '1967'), ('1968', '1968'), ('1969', '1969'), ('1970', '1970'), ('1971', '1971'), ('1972', '1972'), ('1973', '1973'), ('1974', '1974'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('Present', 'Present')], default='2022', max_length=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wl1', models.CharField(blank=True, max_length=100, null=True)),
                ('wl2', models.CharField(blank=True, max_length=100, null=True)),
                ('wl3', models.CharField(blank=True, max_length=100, null=True)),
                ('wl4', models.CharField(blank=True, max_length=100, null=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='WEB_cv', to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Skill2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_w1', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w2', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w3', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w4', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w5', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w6', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w7', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w8', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w9', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w10', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w11', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w12', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w13', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w14', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w15', models.CharField(blank=True, max_length=1024, null=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SKILL2_cv', to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Skill1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_w1', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w2', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w3', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w4', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w5', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w6', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w7', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w8', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w9', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w10', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w11', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w12', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w13', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w14', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w15', models.CharField(blank=True, max_length=1024, null=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SKILL1_cv', to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='PImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=app.models.path_and_rename_overwrite)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1', models.CharField(max_length=1024)),
                ('l2', models.CharField(blank=True, max_length=1024, null=True)),
                ('l3', models.CharField(blank=True, max_length=1024, null=True)),
                ('l4', models.CharField(blank=True, max_length=1024, null=True)),
                ('l5', models.CharField(blank=True, max_length=1024, null=True)),
                ('l6', models.CharField(blank=True, max_length=1024, null=True)),
                ('l7', models.CharField(blank=True, max_length=1024, null=True)),
                ('l8', models.CharField(blank=True, max_length=1024, null=True)),
                ('l9', models.CharField(blank=True, max_length=1024, null=True)),
                ('l10', models.CharField(blank=True, max_length=1024, null=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LANG_cv', to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_o', models.CharField(max_length=50)),
                ('job_ws', models.CharField(blank=True, max_length=200, null=True)),
                ('job_l', models.CharField(max_length=50)),
                ('job_sdm', models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('March', 'March'), ('Apr', 'Apr'), ('June', 'June'), ('July', 'July'), ('Aug', 'Aug'), ('Sept', 'Sept'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec'), ('Present', 'Present')], default='Jan', max_length=9)),
                ('job_sdy', models.CharField(choices=[('1950', '1950'), ('1951', '1951'), ('1952', '1952'), ('1953', '1953'), ('1954', '1954'), ('1955', '1955'), ('1956', '1956'), ('1957', '1957'), ('1958', '1958'), ('1959', '1959'), ('1960', '1960'), ('1961', '1961'), ('1962', '1962'), ('1963', '1963'), ('1964', '1964'), ('1965', '1965'), ('1966', '1966'), ('1967', '1967'), ('1968', '1968'), ('1969', '1969'), ('1970', '1970'), ('1971', '1971'), ('1972', '1972'), ('1973', '1973'), ('1974', '1974'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('Present', 'Present')], default='2022', max_length=9)),
                ('job_edm', models.CharField(choices=[('Jan', 'Jan'), ('Feb', 'Feb'), ('March', 'March'), ('Apr', 'Apr'), ('June', 'June'), ('July', 'July'), ('Aug', 'Aug'), ('Sept', 'Sept'), ('Oct', 'Oct'), ('Nov', 'Nov'), ('Dec', 'Dec'), ('Present', 'Present')], default='Jan', max_length=9)),
                ('job_edy', models.CharField(choices=[('1950', '1950'), ('1951', '1951'), ('1952', '1952'), ('1953', '1953'), ('1954', '1954'), ('1955', '1955'), ('1956', '1956'), ('1957', '1957'), ('1958', '1958'), ('1959', '1959'), ('1960', '1960'), ('1961', '1961'), ('1962', '1962'), ('1963', '1963'), ('1964', '1964'), ('1965', '1965'), ('1966', '1966'), ('1967', '1967'), ('1968', '1968'), ('1969', '1969'), ('1970', '1970'), ('1971', '1971'), ('1972', '1972'), ('1973', '1973'), ('1974', '1974'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('Present', 'Present')], default='2022', max_length=9)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JOB_cv', to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='J_Role_Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(blank=True, choices=[('Projects', 'Projects'), ('Achievements', 'Achievements'), ('Responsibilities', 'Responsibilities'), ('Awards', 'Awards'), ('Publications', 'Publications'), ('Achievements', 'Achievements'), ('Performance', 'Performance'), ('Acquisition', 'Acquisition'), ('Participation', 'Participation')], default='Projects', max_length=20, null=True)),
                ('cat_p1', models.CharField(max_length=1024)),
                ('cat_p2', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p3', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p4', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p5', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p6', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p7', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p8', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p9', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p10', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p11', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p12', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p13', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p14', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p15', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p16', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p17', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p18', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p19', models.CharField(blank=True, max_length=1024, null=True)),
                ('cat_p20', models.CharField(blank=True, max_length=1024, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CAT_job', to='app.job')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CAT_role', to='app.j_role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CAT_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='j_role',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ROLE_job', to='app.job'),
        ),
        migrations.AddField(
            model_name='j_role',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ROLE_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.CharField(max_length=1500)),
                ('outro_text', models.CharField(blank=True, max_length=1500, null=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='INTRO_cv', to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_s', models.CharField(max_length=100)),
                ('edu_d', models.CharField(max_length=100)),
                ('edu_l', models.CharField(blank=True, max_length=100, null=True)),
                ('edu_sdy', models.CharField(choices=[('1950', '1950'), ('1951', '1951'), ('1952', '1952'), ('1953', '1953'), ('1954', '1954'), ('1955', '1955'), ('1956', '1956'), ('1957', '1957'), ('1958', '1958'), ('1959', '1959'), ('1960', '1960'), ('1961', '1961'), ('1962', '1962'), ('1963', '1963'), ('1964', '1964'), ('1965', '1965'), ('1966', '1966'), ('1967', '1967'), ('1968', '1968'), ('1969', '1969'), ('1970', '1970'), ('1971', '1971'), ('1972', '1972'), ('1973', '1973'), ('1974', '1974'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('Present', 'Present')], default='2022', max_length=9)),
                ('edu_edy', models.CharField(choices=[('1950', '1950'), ('1951', '1951'), ('1952', '1952'), ('1953', '1953'), ('1954', '1954'), ('1955', '1955'), ('1956', '1956'), ('1957', '1957'), ('1958', '1958'), ('1959', '1959'), ('1960', '1960'), ('1961', '1961'), ('1962', '1962'), ('1963', '1963'), ('1964', '1964'), ('1965', '1965'), ('1966', '1966'), ('1967', '1967'), ('1968', '1968'), ('1969', '1969'), ('1970', '1970'), ('1971', '1971'), ('1972', '1972'), ('1973', '1973'), ('1974', '1974'), ('1975', '1975'), ('1976', '1976'), ('1977', '1977'), ('1978', '1978'), ('1979', '1979'), ('1980', '1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985', '1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'), ('1990', '1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995', '1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'), ('2000', '2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005', '2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('Present', 'Present')], default='2022', max_length=9)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EDU_cv', to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(max_length=200)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='BIO_cv', to='app.cv')),
            ],
        ),
    ]
