# Generated by Django 3.2.8 on 2021-11-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211102_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edu',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EDU_cv', to='app.cv'),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
