# Generated by Django 3.2.8 on 2022-07-25 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_web_wl5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web',
            name='wl5',
        ),
    ]
