# Generated by Django 3.2.8 on 2021-11-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='cv',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='JOBS_cv', to='app.cv'),
        ),
    ]
