# Generated by Django 3.2.8 on 2021-11-14 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
