# Generated by Django 3.2.8 on 2021-11-15 08:40

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_img_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimg',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=app.models.path_and_rename_overwrite),
        ),
        migrations.DeleteModel(
            name='Img',
        ),
    ]
