# Generated by Django 3.2.8 on 2021-11-16 14:41

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20211115_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='pimg',
            name='url',
            field=models.CharField(default='1', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pimg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.path_and_rename_overwrite),
        ),
        migrations.CreateModel(
            name='PImg1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=app.models.path_and_rename_overwrite)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
