# Generated by Django 3.2.8 on 2021-11-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20211116_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_ed',
            field=models.CharField(help_text='Please use the following format: <em>MM/YYYY</em>.', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_sd',
            field=models.CharField(help_text='Please use the following format: <em>MM/YYYY</em>.', max_length=20),
        ),
        migrations.DeleteModel(
            name='PImg1',
        ),
    ]
