# Generated by Django 3.2.8 on 2021-11-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20211118_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='lang',
        ),
        migrations.AddField(
            model_name='bio',
            name='wl1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='wl2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='wl3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='wl4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
