# Generated by Django 3.2.8 on 2021-11-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20211118_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='bio',
            name='lang',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
