# Generated by Django 3.2.8 on 2021-11-22 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_bio_lang'),
    ]

    operations = [
        migrations.CreateModel(
            name='JRole',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('role_r', models.CharField(max_length=50)),
                ('role_l', models.CharField(blank=True, max_length=50, null=True)),
                ('role_sd', models.CharField(blank=True, help_text='Please use the following format: <em>MM/YYYY</em>.', max_length=20, null=True)),
                ('role_ed', models.CharField(help_text='Please use the following format: <em>MM/YYYY</em>.', max_length=20)),
                ('job_d', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_d',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_r',
        ),
        migrations.AddField(
            model_name='bio',
            name='surname',
            field=models.CharField(default='Smith', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='job_ws',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='intro_text',
            field=models.CharField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='bio',
            name='lang',
            field=models.CharField(blank=True, help_text='Please separate langauges with a comma: English, German, French', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='outro_text',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='skill_t',
            field=models.CharField(blank=True, help_text='Please separate tool skills with a comma: Office, Microsoft Teams, Adobe Suite', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='skill_w',
            field=models.CharField(blank=True, help_text='Please separate workflow skills with a comma: Project Management, Team Leadership, Client Management', max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='cv',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='JOB_cv', to='app.cv'),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='JRoleCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(help_text="Category name, EX: 'Projects I worked on', 'Responsibilities' etc... ", max_length=1024)),
                ('cat_p', models.CharField(help_text='Please separate elements with a comma: Project X, Project Y, Project Z', max_length=1024)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Cat_role', to='app.jrole')),
            ],
        ),
        migrations.AddField(
            model_name='jrole',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ROLE_job', to='app.job'),
        ),
    ]
