# Generated by Django 3.2.8 on 2021-11-22 06:58

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211122_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jrolecat',
            name='role',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_ed',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_sd',
        ),
        migrations.AddField(
            model_name='job',
            name='job_edm',
            field=models.CharField(default=app.models.current_m, max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='job_edy',
            field=models.IntegerField(default=app.models.current_y, max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='job_sdm',
            field=models.CharField(default=app.models.current_m, max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='job_sdy',
            field=models.IntegerField(default=app.models.current_y, max_length=20),
        ),
        migrations.DeleteModel(
            name='JRole',
        ),
        migrations.DeleteModel(
            name='JRoleCat',
        ),
    ]
