# Generated by Django 3.2.8 on 2021-11-22 06:58

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20211122_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_edy',
            field=models.IntegerField(default=app.models.current_y),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_sdy',
            field=models.IntegerField(default=app.models.current_y),
        ),
    ]
