# Generated by Django 3.2.8 on 2021-11-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20211122_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='JRole',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('role_r', models.CharField(max_length=50)),
                ('role_l', models.CharField(blank=True, max_length=50, null=True)),
                ('role_d', models.CharField(blank=True, max_length=1024, null=True)),
                ('role_sdm', models.CharField(blank=True, max_length=20, null=True)),
                ('role_sdy', models.IntegerField(blank=True, null=True, verbose_name='year')),
                ('role_edm', models.CharField(blank=True, max_length=20, null=True)),
                ('role_edy', models.IntegerField(blank=True, null=True, verbose_name='year')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ROLE_job', to='app.job')),
            ],
        ),
        migrations.CreateModel(
            name='JRoleCat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(help_text="Category name, EX: 'Projects I worked on', 'Responsibilities' etc... ", max_length=1024)),
                ('cat_p', models.CharField(help_text='Please separate elements with a comma: Project X, Project Y, Project Z', max_length=1024)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CAT_role', to='app.jrole')),
            ],
        ),
    ]
