# Generated by Django 3.2.8 on 2021-11-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_jrole_jrolecat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_edm',
            field=models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (6, '7'), (7, '8'), (8, '9'), (9, '10'), (10, '11'), (11, '12'), (12, '13'), (13, '14'), (14, '15'), (15, '16'), (16, '17'), (17, '18'), (18, '19'), (19, '20')], default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_edy',
            field=models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (6, '7'), (7, '8'), (8, '9'), (9, '10'), (10, '11'), (11, '12'), (12, '13'), (13, '14'), (14, '15'), (15, '16'), (16, '17'), (17, '18'), (18, '19'), (19, '20')], default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_sdm',
            field=models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (6, '7'), (7, '8'), (8, '9'), (9, '10'), (10, '11'), (11, '12'), (12, '13'), (13, '14'), (14, '15'), (15, '16'), (16, '17'), (17, '18'), (18, '19'), (19, '20')], default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_sdy',
            field=models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (6, '7'), (7, '8'), (8, '9'), (9, '10'), (10, '11'), (11, '12'), (12, '13'), (13, '14'), (14, '15'), (15, '16'), (16, '17'), (17, '18'), (18, '19'), (19, '20')], default=0),
        ),
        migrations.AlterField(
            model_name='jrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jrole',
            name='role_edy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jrole',
            name='role_sdy',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
