# Generated by Django 3.2.8 on 2021-11-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20211122_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JOB_cv', to='app.cv'),
        ),
    ]
