# Generated by Django 3.2.8 on 2021-11-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20211123_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jrolecat',
            name='role',
        ),
        migrations.DeleteModel(
            name='JRole',
        ),
        migrations.DeleteModel(
            name='JRoleCat',
        ),
    ]
