# Generated by Django 3.2.8 on 2021-11-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_jrole_jrolecat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jrolecat',
            name='role',
        ),
        migrations.DeleteModel(
            name='JRole',
        ),
        migrations.DeleteModel(
            name='JRoleCat',
        ),
    ]
