# Generated by Django 3.2.8 on 2021-11-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_j_role_j_role_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='j_role',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ROLE_job', to='app.job'),
        ),
        migrations.AlterField(
            model_name='j_role_cat',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CAT_role', to='app.j_role'),
        ),
    ]
