# Generated by Django 3.2.8 on 2021-11-23 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20211123_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='j_role_cat',
            name='role',
        ),
        migrations.DeleteModel(
            name='J_Role',
        ),
        migrations.DeleteModel(
            name='J_Role_Cat',
        ),
    ]
