# Generated by Django 3.2.8 on 2021-11-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20211126_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bio',
            name='lang',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='j_role_cat',
            name='cat',
            field=models.CharField(blank=True, choices=[('Projects', 'Projects'), ('Achievements', 'Achievements'), ('Responsibilities', 'Responsibilities'), ('Awards', 'Awards'), ('Publications', 'Publications'), ('Achievements', 'Achievements'), ('Performance', 'Performance'), ('Acquisition', 'Acquisition'), ('Participation', 'Participation')], default='Projects', max_length=20, null=True),
        ),
    ]
