# Generated by Django 3.2.8 on 2021-11-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20211126_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='j_role_cat',
            old_name='cat_p',
            new_name='cat_p1',
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p10',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p11',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p12',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p13',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p14',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p15',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p16',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p17',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p18',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p19',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p2',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p20',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p3',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p4',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p5',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p6',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p7',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p8',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='j_role_cat',
            name='cat_p9',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
