# Generated by Django 3.2.8 on 2021-11-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20211126_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bio',
            old_name='lang',
            new_name='l1',
        ),
        migrations.AddField(
            model_name='bio',
            name='l10',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='l2',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='l3',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='l4',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='l5',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='l6',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='l7',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='l8',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='bio',
            name='l9',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
