# Generated by Django 3.2.8 on 2021-11-27 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20211126_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='intro_text',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='l1',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='l10',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='l2',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='l3',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='l4',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='l5',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='l6',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='l7',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='l8',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='l9',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='outro_text',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='skill_t',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='skill_w',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='wl1',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='wl2',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='wl3',
        ),
        migrations.RemoveField(
            model_name='bio',
            name='wl4',
        ),
        migrations.CreateModel(
            name='Web',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wl1', models.CharField(blank=True, max_length=100, null=True)),
                ('wl2', models.CharField(blank=True, max_length=100, null=True)),
                ('wl3', models.CharField(blank=True, max_length=100, null=True)),
                ('wl4', models.CharField(blank=True, max_length=100, null=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='WEB_cv', to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_w1', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w2', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w3', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w4', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w5', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w6', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w7', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w8', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w9', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w10', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w11', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w12', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w13', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w14', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w15', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w16', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w17', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w18', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w19', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w20', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w21', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w22', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w23', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w24', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w25', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w26', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w27', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w28', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w29', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w30', models.CharField(blank=True, max_length=1024, null=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SKILL_cv', to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1', models.CharField(max_length=1024)),
                ('l2', models.CharField(blank=True, max_length=1024, null=True)),
                ('l3', models.CharField(blank=True, max_length=1024, null=True)),
                ('l4', models.CharField(blank=True, max_length=1024, null=True)),
                ('l5', models.CharField(blank=True, max_length=1024, null=True)),
                ('l6', models.CharField(blank=True, max_length=1024, null=True)),
                ('l7', models.CharField(blank=True, max_length=1024, null=True)),
                ('l8', models.CharField(blank=True, max_length=1024, null=True)),
                ('l9', models.CharField(blank=True, max_length=1024, null=True)),
                ('l10', models.CharField(blank=True, max_length=1024, null=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='LANG_cv', to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.CharField(max_length=1500)),
                ('outro_text', models.CharField(blank=True, max_length=1500, null=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='INTRO_cv', to='app.cv')),
            ],
        ),
    ]
