# Generated by Django 3.2.8 on 2021-11-27 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_auto_20211127_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_w1', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w2', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w3', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w4', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w5', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w6', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w7', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w8', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w9', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w10', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w11', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w12', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w13', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w14', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w15', models.CharField(blank=True, max_length=1024, null=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SKILL1_cv', to='app.cv')),
            ],
        ),
        migrations.CreateModel(
            name='Skill2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_w1', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w2', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w3', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w4', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w5', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w6', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w7', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w8', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w9', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w10', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w11', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w12', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w13', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w14', models.CharField(blank=True, max_length=1024, null=True)),
                ('skill_w15', models.CharField(blank=True, max_length=1024, null=True)),
                ('cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='SKILL2_cv', to='app.cv')),
            ],
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
