# Generated by Django 3.2.8 on 2021-12-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20211127_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='edu_l',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
